blogs/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from . import views


app_name = 'blogs'
urlpatterns = [
    path(
        '',
        views.HomeView.as_view(),
        name='home'
    ),
    path(
        'login/',
        views.BlogLoginView.as_view(),
        name='login'
    ),
    path(
        'logout/',
        LogoutView.as_view(),
        name='logout'
    ),
    path(
        'post-create/',
        views.PostCreateView.as_view(),
        name='post-create'
    ),
    path(
        'post-detail/<int:pk>/',
        views.PostDetailView.as_view(),
        name='post-detail',
    ),
    path(
        'post-detail/<int:pk>/delete/',
        views.PostDeleteView.as_view(),
        name='post-delete',
    ),
    path(
        'blogs/',
        views.BlogListView.as_view(),
        name='blogs',
    ),
    path(
        'subscribe/',
        views.SubscribeBlogView.as_view(),
        name='subscribe',
    ),
    path(
        'unsubscribe/',
        views.UnsubscribeBlogView.as_view(),
        name='unsubscribe',
    ),
    path(
        'read/',
        views.ReadPostView.as_view(),
        name='read',
    ),
    path(
        'unread/',
        views.UnreadPostView.as_view(),
        name='unread',
    ),
    path(
        'blog-posts/',
        views.BlogPostListView.as_view(),
        name='blog-posts',
    ),
    path(
        'read-posts/',
        views.ReadPostListView.as_view(),
        name='read-posts',
    ),
]

main/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView


urlpatterns = [
    path('admin/login/', RedirectView.as_view(pattern_name='blogs:login')),
    path('admin/', admin.site.urls),
    path('', include('blogs.urls')),
]


if settings.DEBUG:
    from django.conf.urls.static import static

    urlpatterns = static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    ) + urlpatterns

    urlpatterns = [
        path('__debug__/', include('debug_toolbar.urls')),
    ] + urlpatterns

blogs/models.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse


User = get_user_model()


class CreatedAtModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        abstract = True


class Blog(CreatedAtModel):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='пользователь')

    def __str__(self):
        return f"{self.user}"

    def check_subscription(self, subscription_blogs):
        if self in subscription_blogs:
            return True

        return False

    class Meta:
        verbose_name = 'блог'
        verbose_name_plural = 'блоги'
        ordering = (
            'created_at',
        )


class Post(CreatedAtModel):
    blog = models.ForeignKey('Blog', on_delete=models.CASCADE, verbose_name='блог')
    title = models.CharField(max_length=settings.LEN, verbose_name='заголовок')
    text = models.TextField(verbose_name='текст')

    def __str__(self):
        return f"{self.blog} / {self.title} / {self.created_at.strftime('%d.%m.%Y')}"

    def check_read(self, user_subscription):
        if self in user_subscription.read_posts.all():
            return True

        return False

    def check_own(self, user_blog):

        if self.blog == user_blog:
            return True

        return False

    def get_absolute_url(self):
        return reverse(
            'blogs:post-detail',
            kwargs={'pk': self.pk}
        )

    class Meta:
        verbose_name = 'пост'
        verbose_name_plural = 'посты'
        ordering = (
            'created_at',
        )


class Subscription(CreatedAtModel):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='пользователь')
    blogs = models.ManyToManyField('Blog', verbose_name='блоги')

    read_posts = models.ManyToManyField('Post', verbose_name='прочитанные посты')

    def __str__(self):
        return f"{self.user}"

    class Meta:
        verbose_name = 'подписка'
        verbose_name_plural = 'подписки'
        ordering = (
            'created_at',
        )

blogs/forms.py
from django import forms

from .models import Post

from .services import get_user_blog


class PostForm(forms.ModelForm):

    def save(self, user, commit=True):
        post = super().save(commit=False)
        user_blog = get_user_blog(user=user)
        post.blog = user_blog

        if commit:
            post.save()
            self.save_m2m()

        return post

    class Meta:
        model = Post
        fields = (
            'title',
            'text',
        )

blogs/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views import generic

from .forms import PostForm
from .models import Blog, Post

from .services import (
    get_user_blog,
    get_user_subscription,
    get_user_subscriptions_blogs,
    get_user_subscriptions_posts,
    get_user_subscriptions_unread_posts,
    subscribe_to_blog,
    unsubscribe_from_blog,
    read_post,
    unread_post,
)


class BlogLoginView(LoginView):
    template_name = 'blogs/login-form.html'


class HomeView(LoginRequiredMixin, generic.ListView):
    template_name = 'blogs/home.html'
    paginate_by = 50

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'user_subscription': self.user_subscription,
        })
        return context

    def get_queryset(self):
        self.user_subscription = get_user_subscription(self.request.user)
        blogs = get_user_subscriptions_blogs(self.user_subscription)
        posts = get_user_subscriptions_posts(blogs)
        unread_posts = get_user_subscriptions_unread_posts(self.user_subscription, posts)
        return unread_posts.order_by('-created_at')


class PostCreateView(LoginRequiredMixin, generic.CreateView):
    template_name_suffix = '-form'
    model = Post
    form_class = PostForm

    def form_valid(self, form):
        self.object = form.save(user=self.request.user)
        return redirect(self.get_success_url())


class PostDetailView(LoginRequiredMixin, generic.DetailView):
    template_name_suffix = '-detail'
    model = Post

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user_blog = get_user_blog(self.request.user)
        context.update({
            'user_blog': user_blog
        })
        return context


class BlogListView(LoginRequiredMixin, generic.ListView):
    template_name_suffix = '-list'
    model = Blog
    paginate_by = 50

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user_subscription = get_user_subscription(self.request.user)
        blogs = get_user_subscriptions_blogs(user_subscription)
        context.update({'subscription_blogs': blogs})
        return context

    def get_queryset(self):
        qs = Blog.objects.exclude(user=self.request.user).select_related('user')
        return qs


class SubscribeBlogView(LoginRequiredMixin, generic.View):

    def post(self, request):
        blog_pk = request.POST.get('blog_pk')
        blog = get_object_or_404(Blog, pk=blog_pk)

        user_subscription = get_user_subscription(self.request.user)
        subscribe_to_blog(user_subscription, blog)

        return redirect(request.POST.get('back', '/'))


class UnsubscribeBlogView(LoginRequiredMixin, generic.View):

    def post(self, request):
        blog_pk = request.POST.get('blog_pk')
        blog = get_object_or_404(Blog, pk=blog_pk)

        user_subscription = get_user_subscription(self.request.user)
        unsubscribe_from_blog(user_subscription, blog)

        return redirect(request.POST.get('back', '/'))


class ReadPostView(LoginRequiredMixin, generic.View):

    def post(self, request):
        post_pk = request.POST.get('post_pk')
        post = get_object_or_404(Post, pk=post_pk)

        user_subscription = get_user_subscription(self.request.user)
        read_post(user_subscription, post)

        return redirect(request.POST.get('back', '/'))


class UnreadPostView(LoginRequiredMixin, generic.View):

    def post(self, request):
        post_pk = request.POST.get('post_pk')
        post = get_object_or_404(Post, pk=post_pk)

        user_subscription = get_user_subscription(self.request.user)
        unread_post(user_subscription, post)

        return redirect(request.POST.get('back', '/'))


class BlogPostListView(LoginRequiredMixin, generic.ListView):
    template_name = 'blogs/blog-post-list.html'
    model = Post

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'own_blog': self.own_blog,
            'user_blog': self.user_blog
        })
        return context

    def get_queryset(self):
        blog_pk = self.request.GET.get('blog_pk')
        if blog_pk:
            user_blog = get_object_or_404(Blog, pk=blog_pk)
            self.own_blog = 0
        else:
            user_blog = get_user_blog(self.request.user)
            self.own_blog = 1

        self.user_blog = user_blog
        return self.model.objects.filter(blog=user_blog).order_by('-created_at')


class ReadPostListView(LoginRequiredMixin, generic.ListView):
    template_name = 'blogs/home.html'
    paginate_by = 50

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'title': 'Просмотренные посты',
            'user_subscription': self.user_subscription
        })
        return context

    def get_queryset(self):
        self.user_subscription = get_user_subscription(self.request.user)
        return self.user_subscription.read_posts.select_related('blog').all()


class PostDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Post
    success_url = reverse_lazy('blogs:own-posts')

templates/blogs/blog-list.html
{% extends 'empty.html' %}
{% load utils_extras %}

{% block title %}
    Список блогов
{% endblock %}

{% block content %}
    <h1>Список блогов</h1>
    <table class="table">
        <thead>
            <th scope="col" style="width: 10%;">#</th>
            <th scope="col" style="width: 50%;">Блог</th>
            <th scope="col" style="width: 40%;"></th>
        </thead>
        <tbody>
            {% for blog in object_list %}
                <tr>
                    <th scope="row">{{ blog.id }}</th>
                    <td>
                        <a href="{% url 'blogs:blog-posts' %}?blog_pk={{ blog.pk }}">{{ blog }}</a>
                    </td>
                    <td>
                        {% call_method blog 'check_subscription' subscription_blogs as is_signed %}
                        {% if is_signed %}
                            <p class="text-muted">Вы подписаны
                            <a
                                href="#id_unsubscribe_blog"
                                data-toggle="modal"
                                data-whatever="{{ blog.id }}"
                                data-field-id="#id_blog_pk"
                            >
                                Отписаться
                            </a>
                        {% else %}
                            <a
                                href="#id_subscribe_blog"
                                data-toggle="modal"
                                data-whatever="{{ blog.id }}"
                                data-field-id="#id_blog_pk"
                            >
                                Подписаться
                            </a>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

    {% if is_paginated %}
        {% include 'partial/pagination.html' with page_obj=page_obj %}
    {% endif %}

{% endblock %}

{% block modal %}
    <div class="modal fade SetModalValue" id="id_subscribe_blog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Подтвердить действие</h5>
                    <button type="button" class="close" data-dismiss="modal">
                        <span>&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>Вы действительно хотите подписаться на этот блог?</p>
                </div>
                <div class="modal-footer">
                    <form action="{% url 'blogs:subscribe' %}" method="POST">
                        {% csrf_token %}
                        <input type="hidden" name="blog_pk" id="id_blog_pk">
                        <input type="hidden" name="back", value="{{ request.path }}">
                        <button class="btn btn-primary" type="submit">Да</button>
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Отмена</button>
                    </form>
                </div>
            </div> <!-- .modal-content -->
        </div> <!-- .modal-dialog -->
    </div> <!-- .modal -->

    <div class="modal fade SetModalValue" id="id_unsubscribe_blog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Подтвердить действие</h5>
                    <button type="button" class="close" data-dismiss="modal">
                        <span>&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>Вы действительно хотите отписаться от этого блога?</p>
                </div>
                <div class="modal-footer">
                    <form action="{% url 'blogs:unsubscribe' %}" method="POST">
                        {% csrf_token %}
                        <input type="hidden" name="blog_pk" id="id_blog_pk">
                        <input type="hidden" name="back", value="{{ request.path }}">
                        <button class="btn btn-danger" type="submit">Да</button>
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Отмена</button>
                    </form>
                </div>
            </div> <!-- .modal-content -->
        </div> <!-- .modal-dialog -->
    </div> <!-- .modal -->
{% endblock %}

templates/blogs/blog-post-list.html
{% extends 'empty.html' %}
{% load utils_extras %}

{% block title %}
    {% if own_blog %}
        Мой блог
    {% else %}
        Просмотр блога: {{ user_blog }}
    {% endif %}
{% endblock %}

{% block content %}
    {% if own_blog %}
        <h1>Мой блог</h1>
    {% else %}
        <h1>Просмотр блога: {{ user_blog }}</h1>
    {% endif %}
    {% for post in post_list %}
        <div class="alert alert-secondary mr-5">
            <p>
                <strong>
                    <a href="{% url 'blogs:post-detail' pk=post.pk %}">{{ post.title }}</a>
                </strong>
            </p>
            <hr>
            <p>
                {{ post.text }}
            </p>
            <hr>
            <p class="mb-0 text-muted">
                {{ post.created_at|date:'d.m.Y H:i:s'}}
            </p>
        </div>
    {% empty %}
        <div class="alert alert-warning">
            {% if own_blog %}
                <p>У Вас еще нет постов</p>
            {% else %}
                <p>В этом блоге еще нет постов</p>
            {% endif %}
        </div>
    {% endfor %}

    {% if is_paginated %}
        {% include 'partial/pagination.html' with page_obj=page_obj %}
    {% endif %}

{% endblock %}

templates/blogs/email.html
{% extends 'empty-email.html' %}

{% block content %}
    <p>
        Привет!
    </p>
    <p>
        В блог <strong>{{ post.blog }}</strong> добавлен новый пост с заголовком {{ post.title }}.
    </p>
    <p>
        <a href="{{ domain}}{{ post.get_absolute_url }}">Перейти к просмотру.</a>
    </p>
{% endblock %}

templates/blogs/home.html
{% extends 'empty.html' %}
{% load utils_extras %}

{% block title %}
    {{ title|default:'Главная' }}
{% endblock %}

{% block content %}
    <h1>{{ title|default:'Главная' }}</h1>
    {% for post in post_list %}
        <div class="alert alert-secondary mr-5">
            <p>
                <strong>
                    <a href="{% url 'blogs:post-detail' pk=post.pk %}">{{ post.title }}</a>
                </strong>
            </p>
            <hr>
            <p>
                {{ post.text }}
            </p>
            <hr>
            <p class="mb-0 text-muted">
                {{ post.created_at|date:'d.m.Y H:i:s'}}
                <br>
                <a
                    href="#id_unsubscribe_blog"
                    data-toggle="modal"
                    data-whatever="{{ post.blog.id }}"
                    data-field-id="#id_blog_pk"
                >
                    Отписаться от {{ post.blog }}
                </a>
                <br>
                {% call_method post 'check_read' user_subscription as is_read %}
                {% if is_read %}
                    <span class="">Пост прочитан</span>
                    <a
                        href="#id_unread_post"
                        data-toggle="modal"
                        data-whatever="{{ post.id }}"
                        data-field-id="#id_post_pk"
                    >
                        Отметить непрочитанным
                    </a>
                {% else %}
                    <a
                        href="#id_read_post"
                        data-toggle="modal"
                        data-whatever="{{ post.id }}"
                        data-field-id="#id_post_pk"
                    >
                        Отметить прочитанным
                    </a>
                {% endif %}
            </p>
        </div>
    {% empty %}
        <div class="alert alert-warning">
            <p>Нет постов для просмотра</p>
        </div>
    {% endfor %}

    {% if is_paginated %}
        {% include 'partial/pagination.html' with page_obj=page_obj %}
    {% endif %}

{% endblock %}

{% block modal %}
    <div class="modal fade SetModalValue" id="id_unsubscribe_blog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Подтвердить действие</h5>
                    <button type="button" class="close" data-dismiss="modal">
                        <span>&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>Вы действительно хотите отписаться от этого блога?</p>
                </div>
                <div class="modal-footer">
                    <form action="{% url 'blogs:unsubscribe' %}" method="POST">
                        {% csrf_token %}
                        <input type="hidden" name="blog_pk" id="id_blog_pk">
                        <input type="hidden" name="back", value="{{ request.path }}">
                        <button class="btn btn-danger" type="submit">Да</button>
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Отмена</button>
                    </form>
                </div>
            </div> <!-- .modal-content -->
        </div> <!-- .modal-dialog -->
    </div> <!-- .modal -->

    <div class="modal fade SetModalValue" id="id_read_post">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Подтвердить действие</h5>
                    <button type="button" class="close" data-dismiss="modal">
                        <span>&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>Вы действительно хотите отметить этот пост прочитанным?</p>
                </div>
                <div class="modal-footer">
                    <form action="{% url 'blogs:read' %}" method="POST">
                        {% csrf_token %}
                        <input type="hidden" name="post_pk" id="id_post_pk">
                        <input type="hidden" name="back", value="{{ request.path }}">
                        <button class="btn btn-primary" type="submit">Да</button>
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Отмена</button>
                    </form>
                </div>
            </div> <!-- .modal-content -->
        </div> <!-- .modal-dialog -->
    </div> <!-- .modal -->

    <div class="modal fade SetModalValue" id="id_unread_post">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Подтвердить действие</h5>
                    <button type="button" class="close" data-dismiss="modal">
                        <span>&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>Вы действительно хотите отметить этот пост непрочитанным?</p>
                </div>
                <div class="modal-footer">
                    <form action="{% url 'blogs:unread' %}" method="POST">
                        {% csrf_token %}
                        <input type="hidden" name="post_pk" id="id_post_pk">
                        <input type="hidden" name="back", value="{{ request.path }}">
                        <button class="btn btn-danger" type="submit">Да</button>
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Отмена</button>
                    </form>
                </div>
            </div> <!-- .modal-content -->
        </div> <!-- .modal-dialog -->
    </div> <!-- .modal -->
{% endblock %}

templates/blogs/login-form.html
{% extends 'empty.html' %}

{% block title %}
    Вход
{% endblock %}

{% block content %}
    <form action="" method="POST">
        {% csrf_token %}
        <h1>Вход</h1>

        {% if user.is_authenticated %}
            <p class="text-warning">
                Вы вошли как {{ user }}, но у Вас не хватает прав для доступа к этой странице. Есть ли у вас другой аккаунт?
            </p>
        {% endif %}

        {% for error in form.non_field_errors %}
            <p class="text-danger">{{ error }}</p>
        {% endfor %}

        <div class="form-group">
            {{ form.username.label_tag }}
            <input
                class="form-control"
                type="text"
                name="{{ form.username.html_name }}"
                id="{{ form.username.id_for_label }}"
                value="{{ form.username.value|default_if_none:'' }}"
                required
            >
            {% for error in form.username.errors %}
                <span class="text-danger">{{ error }}</span>
            {% endfor %}
        </div>

        <div class="form-group">
            {{ form.password.label_tag }}
            <input
                class="form-control"
                type="password"
                name="{{ form.password.html_name }}"
                id="{{ form.password.id_for_label }}"
                required
            >
            {% for error in form.password.errors %}
                <span class="text-danger">{{ error }}</span>
            {% endfor %}
        </div>

        <button type="submit" class="btn btn-primary">Войти</button>
    </form>

{% endblock %}

templates/blogs/own-post-list.html
{% extends 'empty.html' %}
{% load utils_extras %}

{% block title %}
    Мой блог
{% endblock %}

{% block content %}
    <h1>Мой блог</h1>
    {% for post in post_list %}
        <div class="alert alert-secondary mr-5">
            <p>
                <strong>
                    <a href="{% url 'blogs:post-detail' pk=post.pk %}">{{ post.title }}</a>
                </strong>
            </p>
            <hr>
            <p>
                {{ post.text }}
            </p>
            <hr>
            <p class="mb-0 text-muted">
                {{ post.created_at|date:'d.m.Y H:i:s'}}
            </p>
        </div>
    {% empty %}
        <div class="alert alert-warning">
            <p>У Вас еще нет постов</p>
        </div>
    {% endfor %}

    {% if is_paginated %}
        {% include 'partial/pagination.html' with page_obj=page_obj %}
    {% endif %}

{% endblock %}

templates/blogs/post-detail.html
{% extends 'empty.html' %}
{% load utils_extras %}

{% block title %}
    Пост #{{ object.pk }}
{% endblock %}

{% block content %}
    <h1>Пост #{{ object.pk }}</h1>

    {% call_method post 'check_own' user_blog as is_own %}

    {% if is_own %}
        <div class="mb-4">
            <div class="btn-group">
                <a
                    href="#id_post_delete"
                    data-toggle="modal"
                    class="btn btn-danger"
                >
                    Удалить
                </a>
            </div>
        </div>
    {% endif %}

    <table class="table table-bordered">
        <tr>
            <th>Блог</th>
            <td>
                <a
                    {% if is_own %}
                        href="{% url 'blogs:blog-posts' %}"
                    {% else %}
                        href="{% url 'blogs:blog-posts' %}?blog_pk={{ object.blog.pk }}"
                    {% endif %}
                    >{{ object.blog }}</a>
            </td>
        </tr>
        <tr>
            <th>Заголовок</th>
            <td>{{ object.title }}</td>
        </tr>
        <tr>
            <th>Текст</th>
            <td>{{ object.text }}</td>
        </tr>
        <tr>
            <th>Когда добавлен</th>
            <td>{{ object.created_at|date:'d.m.Y H:i:s' }}</td>
        </tr>
    </table>
{% endblock %}

{% block modal %}
    <div class="modal fade" id="id_post_delete">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Подтвердить действие</h5>
                    <button type="button" class="close" data-dismiss="modal">
                        <span>&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>Вы уверены, что хотите удалить этот пост?</p>
                </div>
                <div class="modal-footer">
                    <form action="{% url 'blogs:post-delete' pk=object.pk %}" method="POST">
                        {% csrf_token %}
                        <button class="btn btn-danger" type="submit">Да</button>
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Отмена</button>
                    </form>
                </div>
            </div> <!-- .modal-content -->
        </div> <!-- .modal-dialog -->
    </div> <!-- .modal -->
{% endblock %}

templates/blogs/post-form.html
{% extends 'empty.html' %}

{% block title %}
    Добавление поста
{% endblock %}

{% block content %}
    <form action="" method="POST">
        {% csrf_token %}
        <h1>Добавление поста</h1>

        {% for error in form.non_field_errors %}
            <p class="text-danger">{{ error }}</p>
        {% endfor %}

        <div class="form-group">
            {{ form.title.label_tag }}
            <input
                class="form-control"
                type="text"
                name="{{ form.title.html_name }}"
                id="{{ form.title.id_for_label }}"
                value="{{ form.title.value|default_if_none:'' }}"
                required
            >
            {% for error in form.title.errors %}
                <span class="text-danger">{{ error }}</span>
            {% endfor %}
        </div>

        <div class="form-group">
            {{ form.text.label_tag }}
            <textarea
                class="form-control"
                name="{{ form.text.html_name }}"
                id="{{ form.text.id_for_label }}"
                required
            >{{ form.text.value|default_if_none:'' }}</textarea>
            {% for error in form.text.errors %}
                <span class="text-danger">{{ error }}</span>
            {% endfor %}
        </div>

        <button type="submit" class="btn btn-primary">Сохранить</button>
    </form>

{% endblock %}