blogs/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from . import views


app_name = 'blogs'
urlpatterns = [
    path(
        '',
        views.HomeView.as_view(),
        name='home'
    ),
    path(
        'login/',
        views.BlogLoginView.as_view(),
        name='login'
    ),
    path(
        'logout/',
        LogoutView.as_view(),
        name='logout'
    ),
    path(
        'post-create/',
        views.PostCreateView.as_view(),
        name='post-create'
    ),
    path(
        'post-detail/<int:pk>/',
        views.PostDetailView.as_view(),
        name='post-detail',
    ),
    path(
        'post-detail/<int:pk>/delete/',
        views.PostDeleteView.as_view(),
        name='post-delete',
    ),
    path(
        'blogs/',
        views.BlogListView.as_view(),
        name='blogs',
    ),
    path(
        'subscribe/',
        views.SubscribeBlogView.as_view(),
        name='subscribe',
    ),
    path(
        'unsubscribe/',
        views.UnsubscribeBlogView.as_view(),
        name='unsubscribe',
    ),
    path(
        'read/',
        views.ReadPostView.as_view(),
        name='read',
    ),
    path(
        'unread/',
        views.UnreadPostView.as_view(),
        name='unread',
    ),
    path(
        'blog-posts/',
        views.BlogPostListView.as_view(),
        name='blog-posts',
    ),
    path(
        'read-posts/',
        views.ReadPostListView.as_view(),
        name='read-posts',
    ),
]

main/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView


urlpatterns = [
    path('admin/login/', RedirectView.as_view(pattern_name='blogs:login')),
    path('admin/', admin.site.urls),
    path('', include('blogs.urls')),
]


if settings.DEBUG:
    from django.conf.urls.static import static

    urlpatterns = static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    ) + urlpatterns

    urlpatterns = [
        path('__debug__/', include('debug_toolbar.urls')),
    ] + urlpatterns

templates/empty-email.html
<!DOCTYPE html>
<html lang="ru">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body>
        {% block content %}{% endblock %}
    </body>
</html>

templates/empty.html
{% load render_bundle from webpack_loader %}
{% load menu_extras %}

<!doctype html>
<html lang="ru">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        {% render_bundle 'main' 'css' %}
        <title>Блог | {% block title %}{% endblock %}</title>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <a class="navbar-brand" href="/">Блог</a>
            <button
                class="navbar-toggler"
                type="button"
                data-toggle="collapse"
                data-target="#navbarColor01"
                aria-controls="navbarColor01"
                aria-expanded="false"
                aria-label="Toggle navigation"
            >
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarColor01">
                <ul class="navbar-nav mr-auto"></ul>
                {% if request.user.is_authenticated %}
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <span class="navbar-text">{{ request.user }}</span>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'blogs:logout' %}">Выйти</a>
                        </li>
                    </ul>
                {% else %}
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'blogs:login' %}">Войти</a>
                        </li>
                    </ul>
                {% endif %}
            </div>
        </nav>

        <div class="container-fluid mt-4">
            <div class="row">
                <div class="col-md-8 col-lg-9 order-md-2 mb-5">
                    {% block content %}{% endblock %}
                </div>
                <div class="col-md-4 col-lg-3">
                    <h3>Меню</h3>
                    {% get_menu as menu %}
                    <div class="list-group order-md-1">
                        {% for menu_item in menu %}
                            <a href="{{ menu_item.url }}" class="list-group-item list-group-item-action d-flex justify-content-between align-items-center">
                                {{ menu_item.title }}
                            </a>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
        {% block modal %}{% endblock %}
        {% render_bundle 'main' 'js' %}
    </body>
</html>